/* Generated by Yosys 0.58+74 (git sha1 b510c3616, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

(* dynports =  1  *)
(* hdlname = "uart_rx" *)
(* src = "./src/rx.v:1.1-117.10" *)
module \$paramod$6829b04ab2b1cee1ae540aec570b9e272ef0d6cf\uart_rx (clk, rst_n, uart_rxd, uart_rx_en, uart_rx_break, uart_rx_valid, uart_rx_data);
  (* src = "./src/rx.v:7.14-7.17" *)
  input clk;
  wire clk;
  (* src = "./src/rx.v:8.14-8.19" *)
  input rst_n;
  wire rst_n;
  (* src = "./src/rx.v:9.14-9.22" *)
  input uart_rxd;
  wire uart_rxd;
  (* src = "./src/rx.v:10.14-10.24" *)
  input uart_rx_en;
  wire uart_rx_en;
  (* src = "./src/rx.v:11.15-11.28" *)
  output uart_rx_break;
  wire uart_rx_break;
  (* src = "./src/rx.v:12.15-12.28" *)
  output uart_rx_valid;
  wire uart_rx_valid;
  (* src = "./src/rx.v:13.35-13.47" *)
  output [7:0] uart_rx_data;
  wire [7:0] uart_rx_data;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  (* force_downto = 32'd1 *)
  (* src = "./src/rx.v:78.22-78.40|/usr/local/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [3:0] _31_;
  (* force_downto = 32'd1 *)
  (* src = "./src/rx.v:78.22-78.40|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _32_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [0:0] _33_;
  (* src = "./src/rx.v:24.13-24.24" *)
  wire [3:0] bit_counter;
  (* src = "./src/rx.v:25.7-25.17" *)
  wire bit_sample;
  (* src = "./src/rx.v:23.29-23.42" *)
  wire [0:0] cycle_counter;
  wire [1:0] fsm_state;
  wire [1:0] n_fsm_state;
  (* src = "./src/rx.v:45.8-45.16" *)
  wire next_bit;
  (* src = "./src/rx.v:22.28-22.41" *)
  wire [7:0] recieved_data;
  (* src = "./src/rx.v:20.7-20.14" *)
  wire rxd_reg;
  (* src = "./src/rx.v:21.7-21.16" *)
  wire rxd_reg_0;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _34_ (
    .I(_33_),
    .O(_17_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _35_ (
    .I(rst_n),
    .O(_00_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _36_ (
    .I(_33_),
    .O(_15_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _37_ (
    .I(_33_),
    .O(_13_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _38_ (
    .I(_33_),
    .O(_11_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _39_ (
    .I(_33_),
    .O(_09_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _40_ (
    .I(_33_),
    .O(_07_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _41_ (
    .I(_33_),
    .O(_05_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _42_ (
    .I(_33_),
    .O(_03_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _43_ (
    .I(rst_n),
    .O(_01_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _44_ (
    .I(rst_n),
    .O(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _45_ (
    .I(rst_n),
    .O(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _46_ (
    .I(rst_n),
    .O(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _47_ (
    .I(rst_n),
    .O(_08_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _48_ (
    .I(rst_n),
    .O(_10_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _49_ (
    .I(rst_n),
    .O(_12_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _50_ (
    .I(rst_n),
    .O(_14_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _51_ (
    .I(rst_n),
    .O(_16_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _52_ (
    .I(rst_n),
    .O(_18_)
  );
  sky130_fd_sc_hd__clkinv_1 _53_ (
    .A(bit_counter[0]),
    .Y(_31_[0])
  );
  sky130_fd_sc_hd__xor2_1 _54_ (
    .A(bit_counter[0]),
    .B(bit_counter[1]),
    .X(_32_[1])
  );
  sky130_fd_sc_hd__nand3_1 _55_ (
    .A(bit_counter[0]),
    .B(bit_counter[1]),
    .C(bit_counter[2]),
    .Y(_22_)
  );
  sky130_fd_sc_hd__a21oi_1 _56_ (
    .A1(bit_counter[0]),
    .A2(bit_counter[1]),
    .B1(bit_counter[2]),
    .Y(_23_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _57_ (
    .A(_22_),
    .SLEEP(_23_),
    .X(_32_[2])
  );
  sky130_fd_sc_hd__xnor2_1 _58_ (
    .A(bit_counter[3]),
    .B(_22_),
    .Y(_32_[3])
  );
  sky130_fd_sc_hd__and2_0 _59_ (
    .A(fsm_state[1]),
    .B(fsm_state[0]),
    .X(uart_rx_valid)
  );
  sky130_fd_sc_hd__clkinv_1 _60_ (
    .A(uart_rx_valid),
    .Y(_33_)
  );
  sky130_fd_sc_hd__nand2b_1 _61_ (
    .A_N(fsm_state[0]),
    .B(fsm_state[1]),
    .Y(_24_)
  );
  sky130_fd_sc_hd__clkinv_1 _62_ (
    .A(_24_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__nand2_1 _63_ (
    .A(rst_n),
    .B(_21_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__nor2_1 _64_ (
    .A(fsm_state[1]),
    .B(fsm_state[0]),
    .Y(_25_)
  );
  sky130_fd_sc_hd__nand2_1 _65_ (
    .A(rst_n),
    .B(_25_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__or3_1 _66_ (
    .A(fsm_state[1]),
    .B(fsm_state[0]),
    .C(rxd_reg),
    .X(_26_)
  );
  sky130_fd_sc_hd__or4b_1 _67_ (
    .A(bit_counter[0]),
    .B(bit_counter[1]),
    .C(bit_counter[2]),
    .D_N(bit_counter[3]),
    .X(_27_)
  );
  sky130_fd_sc_hd__o21ai_0 _68_ (
    .A1(_24_),
    .A2(_27_),
    .B1(_26_),
    .Y(n_fsm_state[0])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _69_ (
    .A(fsm_state[0]),
    .SLEEP(fsm_state[1]),
    .X(_28_)
  );
  sky130_fd_sc_hd__a21o_1 _70_ (
    .A1(_21_),
    .A2(_27_),
    .B1(_28_),
    .X(n_fsm_state[1])
  );
  sky130_fd_sc_hd__nor4_1 _71_ (
    .A(recieved_data[5]),
    .B(recieved_data[4]),
    .C(recieved_data[7]),
    .D(recieved_data[6]),
    .Y(_29_)
  );
  sky130_fd_sc_hd__nor4_1 _72_ (
    .A(recieved_data[1]),
    .B(recieved_data[0]),
    .C(recieved_data[3]),
    .D(recieved_data[2]),
    .Y(_30_)
  );
  sky130_fd_sc_hd__and3_1 _73_ (
    .A(uart_rx_valid),
    .B(_29_),
    .C(_30_),
    .X(uart_rx_break)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:100.3-106.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _74_ (
    .C(clk),
    .CE(1'h1),
    .D(n_fsm_state[0]),
    .Q(fsm_state[0]),
    .R(_00_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:100.3-106.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _75_ (
    .C(clk),
    .CE(1'h1),
    .D(n_fsm_state[1]),
    .Q(fsm_state[1]),
    .R(_01_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:108.3-116.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _76_ (
    .C(clk),
    .CE(1'h1),
    .D(rxd_reg_0),
    .Q(rxd_reg),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:108.3-116.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _77_ (
    .C(clk),
    .CE(1'h1),
    .D(uart_rxd),
    .Q(rxd_reg_0),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:82.3-88.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _78_ (
    .C(clk),
    .CE(1'h1),
    .D(rxd_reg),
    .Q(bit_sample),
    .R(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:72.3-80.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _79_ (
    .C(clk),
    .CE(_21_),
    .D(_31_[0]),
    .Q(bit_counter[0]),
    .R(_20_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:72.3-80.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _80_ (
    .C(clk),
    .CE(_21_),
    .D(_32_[1]),
    .Q(bit_counter[1]),
    .R(_20_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:72.3-80.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _81_ (
    .C(clk),
    .CE(_21_),
    .D(_32_[2]),
    .Q(bit_counter[2]),
    .R(_20_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:72.3-80.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _82_ (
    .C(clk),
    .CE(_21_),
    .D(_32_[3]),
    .Q(bit_counter[3]),
    .R(_20_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:59.3-70.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _83_ (
    .C(clk),
    .CE(_21_),
    .D(recieved_data[1]),
    .Q(recieved_data[0]),
    .R(_19_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:59.3-70.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _84_ (
    .C(clk),
    .CE(_21_),
    .D(recieved_data[2]),
    .Q(recieved_data[1]),
    .R(_19_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:59.3-70.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _85_ (
    .C(clk),
    .CE(_21_),
    .D(recieved_data[3]),
    .Q(recieved_data[2]),
    .R(_19_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:59.3-70.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _86_ (
    .C(clk),
    .CE(_21_),
    .D(recieved_data[4]),
    .Q(recieved_data[3]),
    .R(_19_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:59.3-70.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _87_ (
    .C(clk),
    .CE(_21_),
    .D(recieved_data[5]),
    .Q(recieved_data[4]),
    .R(_19_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:59.3-70.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _88_ (
    .C(clk),
    .CE(_21_),
    .D(recieved_data[6]),
    .Q(recieved_data[5]),
    .R(_19_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:59.3-70.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _89_ (
    .C(clk),
    .CE(_21_),
    .D(recieved_data[7]),
    .Q(recieved_data[6]),
    .R(_19_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:59.3-70.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _90_ (
    .C(clk),
    .CE(_21_),
    .D(bit_sample),
    .Q(recieved_data[7]),
    .R(_19_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:37.3-43.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _91_ (
    .C(clk),
    .CE(_03_),
    .D(recieved_data[0]),
    .Q(uart_rx_data[0]),
    .R(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:37.3-43.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _92_ (
    .C(clk),
    .CE(_05_),
    .D(recieved_data[1]),
    .Q(uart_rx_data[1]),
    .R(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:37.3-43.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _93_ (
    .C(clk),
    .CE(_07_),
    .D(recieved_data[2]),
    .Q(uart_rx_data[2]),
    .R(_08_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:37.3-43.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _94_ (
    .C(clk),
    .CE(_09_),
    .D(recieved_data[3]),
    .Q(uart_rx_data[3]),
    .R(_10_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:37.3-43.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _95_ (
    .C(clk),
    .CE(_11_),
    .D(recieved_data[4]),
    .Q(uart_rx_data[4]),
    .R(_12_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:37.3-43.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _96_ (
    .C(clk),
    .CE(_13_),
    .D(recieved_data[5]),
    .Q(uart_rx_data[5]),
    .R(_14_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:37.3-43.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _97_ (
    .C(clk),
    .CE(_15_),
    .D(recieved_data[6]),
    .Q(uart_rx_data[6]),
    .R(_16_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/rx.v:37.3-43.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _98_ (
    .C(clk),
    .CE(_17_),
    .D(recieved_data[7]),
    .Q(uart_rx_data[7]),
    .R(_18_)
  );
  assign _31_[3:1] = bit_counter[3:1];
  assign _32_[0] = _31_[0];
  assign cycle_counter = 1'h0;
  assign next_bit = 1'h1;
endmodule

(* dynports =  1  *)
(* hdlname = "uart_tx" *)
(* src = "./src/tx.v:1.1-104.10" *)
module \$paramod$6829b04ab2b1cee1ae540aec570b9e272ef0d6cf\uart_tx (clk, rst_n, uart_tx_en, uart_tx_data, uart_txd, uart_tx_busy);
  (* src = "./src/tx.v:7.14-7.17" *)
  input clk;
  wire clk;
  (* src = "./src/tx.v:8.14-8.19" *)
  input rst_n;
  wire rst_n;
  (* src = "./src/tx.v:9.14-9.24" *)
  input uart_tx_en;
  wire uart_tx_en;
  (* src = "./src/tx.v:10.35-10.47" *)
  input [7:0] uart_tx_data;
  wire [7:0] uart_tx_data;
  (* src = "./src/tx.v:11.15-11.23" *)
  output uart_txd;
  wire uart_txd;
  (* src = "./src/tx.v:12.15-12.27" *)
  output uart_tx_busy;
  wire uart_tx_busy;
  (* src = "./src/tx.v:22.30-22.43" *)
  wire [13:0] cycle_counter;
  (* src = "./src/tx.v:21.28-21.40" *)
  wire [7:0] data_to_send;
  (* src = "./src/tx.v:24.13-24.22" *)
  wire [2:0] fsm_state;
  (* src = "./src/tx.v:20.7-20.14" *)
  wire txd_reg;
  assign cycle_counter = 14'h0000;
  assign data_to_send = 8'h00;
  assign fsm_state = 3'hx;
  assign txd_reg = 1'h1;
  assign uart_tx_busy = 1'hx;
  assign uart_txd = 1'h1;
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "./src/top.v:4.1-64.10" *)
module top(clk, sw_0, sw_1, uart_rxd, uart_txd, led);
  (* src = "./src/top.v:9.9-9.12" *)
  input clk;
  wire clk;
  (* src = "./src/top.v:10.9-10.13" *)
  input sw_0;
  wire sw_0;
  (* src = "./src/top.v:11.9-11.13" *)
  input sw_1;
  wire sw_1;
  (* src = "./src/top.v:12.14-12.22" *)
  input uart_rxd;
  wire uart_rxd;
  (* src = "./src/top.v:13.15-13.23" *)
  output uart_txd;
  wire uart_txd;
  (* src = "./src/top.v:14.21-14.24" *)
  output [7:0] led;
  wire [7:0] led;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* unused_bits = "0" *)
  wire _10_;
  (* unused_bits = "0" *)
  wire _11_;
  wire _12_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [0:0] _13_;
  (* src = "./src/top.v:24.28-24.35" *)
  wire [7:0] led_reg;
  (* src = "./src/top.v:18.8-18.21" *)
  (* unused_bits = "0" *)
  wire uart_rx_break;
  (* src = "./src/top.v:16.29-16.41" *)
  wire [7:0] uart_rx_data;
  (* src = "./src/top.v:17.8-17.21" *)
  wire uart_rx_valid;
  (* src = "./src/top.v:21.8-21.20" *)
  (* unused_bits = "0" *)
  wire uart_tx_busy;
  (* src = "./src/top.v:20.29-20.41" *)
  wire [7:0] uart_tx_data;
  (* src = "./src/top.v:22.8-22.18" *)
  wire uart_tx_en;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _14_ (
    .I(_13_),
    .O(_00_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _15_ (
    .I(_13_),
    .O(_01_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _16_ (
    .I(_13_),
    .O(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _17_ (
    .I(_13_),
    .O(_03_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _18_ (
    .I(_13_),
    .O(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _19_ (
    .I(_13_),
    .O(_05_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _20_ (
    .I(_13_),
    .O(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV _21_ (
    .I(_13_),
    .O(_07_)
  );
  BUFG _22_ (
    .I(_08_),
    .O(_09_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/top.v:30.3-36.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _23_ (
    .C(_09_),
    .CE(uart_rx_valid),
    .D(uart_rx_data[0]),
    .Q(led_reg[0]),
    .R(_00_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/top.v:30.3-36.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _24_ (
    .C(_09_),
    .CE(uart_rx_valid),
    .D(uart_rx_data[1]),
    .Q(led_reg[1]),
    .R(_01_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/top.v:30.3-36.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _25_ (
    .C(_09_),
    .CE(uart_rx_valid),
    .D(uart_rx_data[2]),
    .Q(led_reg[2]),
    .R(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/top.v:30.3-36.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _26_ (
    .C(_09_),
    .CE(uart_rx_valid),
    .D(uart_rx_data[3]),
    .Q(led_reg[3]),
    .R(_03_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/top.v:30.3-36.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:79.41-79.95" *)
  FDSE #(
    .INIT(1'hx)
  ) _27_ (
    .C(_09_),
    .CE(uart_rx_valid),
    .D(uart_rx_data[4]),
    .Q(led_reg[4]),
    .S(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/top.v:30.3-36.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:79.41-79.95" *)
  FDSE #(
    .INIT(1'hx)
  ) _28_ (
    .C(_09_),
    .CE(uart_rx_valid),
    .D(uart_rx_data[5]),
    .Q(led_reg[5]),
    .S(_05_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/top.v:30.3-36.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:79.41-79.95" *)
  FDSE #(
    .INIT(1'hx)
  ) _29_ (
    .C(_09_),
    .CE(uart_rx_valid),
    .D(uart_rx_data[6]),
    .Q(led_reg[6]),
    .S(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./src/top.v:30.3-36.6|/usr/local/bin/../share/yosys/xilinx/ff_map.v:79.41-79.95" *)
  FDSE #(
    .INIT(1'hx)
  ) _30_ (
    .C(_09_),
    .CE(uart_rx_valid),
    .D(uart_rx_data[7]),
    .Q(led_reg[7]),
    .S(_07_)
  );
  (* keep = 32'd1 *)
  IBUF _31_ (
    .I(clk),
    .O(_08_)
  );
  (* keep = 32'd1 *)
  OBUF _32_ (
    .I(led_reg[0]),
    .O(led[0])
  );
  (* keep = 32'd1 *)
  OBUF _33_ (
    .I(led_reg[1]),
    .O(led[1])
  );
  (* keep = 32'd1 *)
  OBUF _34_ (
    .I(led_reg[2]),
    .O(led[2])
  );
  (* keep = 32'd1 *)
  OBUF _35_ (
    .I(led_reg[3]),
    .O(led[3])
  );
  (* keep = 32'd1 *)
  OBUF _36_ (
    .I(led_reg[4]),
    .O(led[4])
  );
  (* keep = 32'd1 *)
  OBUF _37_ (
    .I(led_reg[5]),
    .O(led[5])
  );
  (* keep = 32'd1 *)
  OBUF _38_ (
    .I(led_reg[6]),
    .O(led[6])
  );
  (* keep = 32'd1 *)
  OBUF _39_ (
    .I(led_reg[7]),
    .O(led[7])
  );
  (* keep = 32'd1 *)
  IBUF _40_ (
    .I(sw_0),
    .O(_13_)
  );
  (* keep = 32'd1 *)
  IBUF _41_ (
    .I(sw_1),
    .O(_10_)
  );
  (* keep = 32'd1 *)
  IBUF _42_ (
    .I(uart_rxd),
    .O(_11_)
  );
  (* keep = 32'd1 *)
  OBUF _43_ (
    .I(_12_),
    .O(uart_txd)
  );
  (* src = "./src/top.v:42.5-50.4" *)
  \$paramod$6829b04ab2b1cee1ae540aec570b9e272ef0d6cf\uart_rx  i_uart_rx (
    .clk(_09_),
    .rst_n(_13_),
    .uart_rx_break(uart_rx_break),
    .uart_rx_data(uart_rx_data),
    .uart_rx_en(1'h1),
    .uart_rx_valid(uart_rx_valid),
    .uart_rxd(_12_)
  );
  (* src = "./src/top.v:56.5-63.4" *)
  \$paramod$6829b04ab2b1cee1ae540aec570b9e272ef0d6cf\uart_tx  i_uart_tx (
    .clk(_09_),
    .rst_n(_13_),
    .uart_tx_busy(uart_tx_busy),
    .uart_tx_data(uart_rx_data),
    .uart_tx_en(uart_rx_valid),
    .uart_txd(_12_)
  );
  assign uart_tx_data = uart_rx_data;
  assign uart_tx_en = uart_rx_valid;
endmodule
